id = "plaintasks"
name = "PlainTasks"
version = "0.1.0"
schema_version = 1
authors = ["Chris Seelus <chris@imeos.com>"]
description = "Syntax highlighting for todo/task files with support for projects, tags, and task states (pending, done, cancelled)."
repository = "https://github.com/cseelus/plaintasks-zed"

[grammars.todo]
repository = "https://github.com/cseelus/tree-sitter-todo"
rev = "b4c615b8a8db36b4ff87bf84b09c054914380dea"
